name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get Existing Labels
        id: get_labels
        run: |
          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.repository }}/labels \
                    | jq -r '.[].name' | paste -sd "," -)
          echo "labels=$LABELS" >> $GITHUB_OUTPUT
      - name: Check for Keywords and Set Labels
        run: |
          IFS=','
          read -ra EXISTING_LABELS <<< "${{steps.get_labels.outputs.labels}}"
          ISSUE_NUMBER=${{ github.event.issue.number }}
          TITLE="${{ github.event.issue.title }}"
          BODY="$(echo "${{ github.event.issue.body }}" | sed 's/`/\\`/g')"
          for label in ${EXISTING_LABELS[@]}; do
              label_name="${label##*:}" # Extracting latter part of label after ":"
              if [[ "$label" == *":"* ]]; then
                  if grep -q "$label_name" <<< "$TITLE" || grep -q "$label_name" <<< "$BODY"; then
                      gh issue edit "$ISSUE_NUMBER" --add-label "$label"
                  fi
              else
                  if grep -q "$label" <<< "$TITLE" || grep -q "$label" <<< "$BODY"; then
                      gh issue edit "$ISSUE_NUMBER" --add-label "$label"
                  fi
              fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
