name: Move Issue forward

on:
  issues:
    types: [opened]

jobs:
  check-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue body contains Issue number reference
        id: check-reference
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          ID_REGEX='#[0-9]+'
          if [[ $ISSUE_BODY =~ $ID_REGEX ]]; then
            echo "ID found: ${BASH_REMATCH[1]}"
            echo "ref=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
              echo "No ID found."
              echo "ref=none" >> $GITHUB_OUTPUT
          fi

      - name: Add comment to previous Issue
        if: steps.check-reference.outputs.ref != 'none'
        run: |
          post_id=${{ steps.check-reference.outputs.ref }}
          issue_number=${{ github.event.issue.number }}
          comment_body="This issue has been moved forward to #${issue_number}"
          COMMENT_API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${post_id}/comments"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          curl -X POST \
          -H "Content-Type: application/json" \
          -H "$AUTH_HEADER" \
          -d "{\"body\": \"${comment_body}\"}" \
          "$COMMENT_API_URL"
