name: Move RFC forward

on:
  issues:
    types: [opened]

jobs:
  check-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue body contains RFC reference
        id: check-rfc-reference
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_BODY=$(echo "$BODY" | sed 's/`/\\`/g')
          ID_REGEX='#([0-9]+)'
          if [[ $ISSUE_BODY =~ $ID_REGEX ]]; then
            echo "ID found: ${BASH_REMATCH[1]}"
            echo "rfc_ref=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
              echo "No ID found."
              echo "rfc_ref=none" >> $GITHUB_OUTPUT
          fi

      - name: Add comment to RFC discussion
        if: steps.check-rfc-reference.outputs.rfc_ref != 'none'
        run: |
          post_id=${{ steps.check-rfc-reference.outputs.rfc_ref }}
          issue_number=${{ github.event.issue.number }}
          comment_body="This issue has been moved forward to #${issue_number}"
          COMMENT_API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${post_id}/comments"
          AUTH_HEADER="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"

          curl -X POST \
          -H "Content-Type: application/json" \
          -H "$AUTH_HEADER" \
          -d "{\"body\": \"${comment_body}\"}" \
          "$COMMENT_API_URL"
